[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Jyri-Matti Lähteenmäki"
Model = "Harmony"
Name = "Harmony"
SerialNumber = "AA:AA:AA:AA:AA:FF"
FirmwareRevision = "100.1.1"


#[[services]]
#type = "Television"
#
#[services.characteristics]
#ConfiguredName = "TV"
#Name = "TV"
#RemoteKey = 0
#SleepDiscoveryMode = 0
#[services.characteristics.Active]
#cmd = "cd harmony; ./cmd/active.sh"
#[services.characteristics.ActiveIdentifier]
#cmd = "cd harmony; ./cmd/active_identifier.sh"
#
#
#[[services]]
#type = "TelevisionSpeaker"
#
#[services.characteristics.Mute]
#cmd = "cd harmony; ./cmd/mute.sh"
#[services.characteristics.VolumeSelector]
#cmd = "cd harmony; ./cmd/volume.sh"
#
#
#[[services]]
#type = "InputSource"
#
#[services.characteristics]
#Name = "Watch TV"
#ConfiguredName = "Watch TV"
#InputSourceType = 3
#InputDeviceType = 1
#[services.characteristics.CurrentVisibilityState]
#cmd = "cd harmony; ./cmd/current_activity.sh 'Watch TV'"
#[services.characteristics.IsConfigured]
#cmd = "cd harmony; ./cmd/start_activity.sh 'Watch TV'"
#
#
#[[services]]
#type = "InputSource"
#
#[services.characteristics]
#Name = "Listen to Music"
#ConfiguredName = "Listen to Music"
#InputSourceType = 8
#InputDeviceType = 5
#[services.characteristics.CurrentVisibilityState]
#cmd = "cd harmony; ./cmd/current_activity.sh 'Listen to Music'"
#[services.characteristics.IsConfigured]
#cmd = "cd harmony; ./cmd/start_activity.sh 'Listen to Music'"






[[services]]
type = "Switch"

[services.characteristics]
Name = "Vol lisää"
ConfiguredName = "Vol lisää"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/volume_up.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Vol vähemmän"
ConfiguredName = "Vol vähemmän"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/volume_down.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Seuraava kanava"
ConfiguredName = "Seuraava kanava"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/channel_up.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Edellinen kanava"
ConfiguredName = "Edellinen kanava"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/channel_down.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Virta"
ConfiguredName = "Virta"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/power.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "TV"
ConfiguredName = "TV"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/start_activity.sh 42565715"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Musiikki"
ConfiguredName = "Musiikki"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/start_activity.sh 42565951"


[[services]]
type = "Switch"

[services.characteristics]
Name = "AppleTV"
ConfiguredName = "AppleTV"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/start_activity.sh 42565987"


[[services]]
type = "Switch"

[services.characteristics]
Name = "BlueRay DVD"
ConfiguredName = "BlueRay DVD"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/start_activity.sh 42566024"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Radio"
ConfiguredName = "Radio"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/start_activity.sh 42566293"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Karaoke"
ConfiguredName = "Karaoke"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/start_activity.sh 50868496"


[[services]]
type = "Switch"

[services.characteristics]
Name = "OK"
ConfiguredName = "OK"
[services.characteristics.On]
cmd = "cd harmony; ./cmd/ok.sh"
